# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Zeeguu Reader' do
#	pod 'Zeeguu-API-iOS', :git => 'https://github.com/mircealungu/Zeeguu-API-iOS'
	pod 'Zeeguu-API-iOS-debug', :git => 'https://github.com/JorritO/Zeeguu-API-iOS'
end

